### ISSUE TITLE
Got undefined is not an object (evaluating 'crypto.pbkdf2Sync.toString') when import to react-native

### ISSUE THREAD

**Issue by dnson** [crypto-browserify/pbkdf2#69] opened 2017-06-13 06:06 UTC

**Comment by calvinmetcalf** [comment] 2017-06-13 12:00
how exactly are you importing this? are you doing

```js
var crypto = require('browserify-crypto');
```

because last I checked react-native doesn't include this by default

**Comment by dnson** [comment] 2017-06-19 09:00
@calvinmetcalf 
I used the babel-plugin-rewrite-require to do that
sth like this:
![image](https://user-images.githubusercontent.com/1157858/27277434-6f7d2a84-5508-11e7-93a6-2b82c2faa3be.png)

**Comment by calvinmetcalf** [comment] 2017-06-19 12:11
so it sounds like that's not working, right, you may want to trouble shoot with the plugin

**Comment by calvinmetcalf** [comment] 2017-06-19 12:14
actually the issue you have is that it isn't grabbing the browser version of packages like it should and is instead grabbing the nodejs version which assumes there is already a crypto object available and just tries to augment it

**Comment by dnson** [comment] 2017-06-20 02:30
@calvinmetcalf I think we need to improve this `crypto.pbkdf2Sync.toString().indexOf('keylen, digest') === -1`. Because sth like when you import to react-native, the code will be minified so it will throw error

**Comment by calvinmetcalf** [comment] 2017-06-20 12:15
so the issue is that it shouldn't be loaded in the first place but whatever your config is isn't respecting the browser field in the package.json

**Comment by dnson** [comment] 2017-06-21 06:07
I mean that 'keylen, digest' will be minified so it will be sth like a,b

**Comment by calvinmetcalf** [comment] 2017-06-21 12:06
again, the fact that you are loading that file while not in node in the first place is a bug but it can't hurt to fail better in that case, see #71

**Comment by fryck** [comment] 2017-06-22 12:43
The problem is, in react native app, index.js is use instead of browser version. I have no problem with another npm packages

**Comment by lnaalisv** [comment] 2017-08-02 08:39
We have a typescript project and we use karma + phantomjs for our unit tests. However when trying to update typescript version our tests break because of this. Removing the if- check from the pdkf2-module makes tests work normally again.

**Comment by calvinmetcalf** [comment] 2017-08-02 13:07
should be fixed and published

**Closed by calvinmetcalf** 2017-08-02 13:07 UTC
Labels: question
